const config = {
  HOST: process.env.NEXT_PUBLIC_CHAT_HOST || 'app.localhost',
  SCHEME: process.env.SCHEME || 'http',
  MONGODB_URI: process.env.MONGODB_URI || '',
  MONGO_PSSWD: process.env.MONGO_PSSWD || '',
  MONGO_USER: process.env.MONGO_USER || '',
  NEXT_PUBLIC_BACKEND_CONNECTOR_KEY: process.env.NEXT_PUBLIC_BACKEND_CONNECTOR_KEY || '',
  NEXT_PUBLIC_BACKEND_TEXT_SIMILARITY: process.env.NEXT_PUBLIC_BACKEND_TEXT_SIMILARITY || '',
  TDB_TTT_SERVICE: process.env.NEXT_PUBLIC_TDB_TTT_SERVICE || '',
  TDB_TTT_SERVICE_AUTHORIZATION: process.env.NEXT_PUBLIC_TDB_TTT_SERVICE_AUTHORIZATION || '',
  NEXT_PUBLIC_BACKEND_CONNECTOR_HOST: process.env.NEXT_PUBLIC_BACKEND_CONNECTOR_HOST || '',
  NEXT_PUBLIC_NEXTAUTH_URL: process.env.NEXT_PUBLIC_NEXTAUTH_URL || '',
  GPT_BEARER_TOKEN: process.env.GPT_BEARER_TOKEN || '',
  SENTRY_IGNORE_API_RESOLUTION_ERROR: process.env.SENTRY_IGNORE_API_RESOLUTION_ERROR || '1',
};

export const TOKEN_USAGE_LIMIT = 10000;
export const AVG_TOKEN_USAGE_PER_REQUEST = 1000;
export const TOKEN_QUOTA_LOCK_DURATION_MS = 5 * 60 * 1000;

export default config;